### PR TITLE
Add Go Store and fix spelling inconsistency

### PR DESCRIPTION
**Pull request by xoltia**
I've added the Go Store and changed the spelling of 'organization' to be consistent.

### CODE REVIEW

**Comment by yaph** [comment]
Sorry, I didn't see your pull request and already added the Go Store in my last commit. Can you update your PR so that it only makes the spelling consistent?

**Comment by yaph** [comment]
Why are there so many changes?

**Comment by xoltia** [comment]
I had to fix a conflict, I'm kinda new to PRs but I don't think there's any difference other than the spelling of organization in the first paragraph. [Branch comparison](https://github.com/yaph/awesome-it-merchandise/compare/master...xoltia:master)

**Comment by yaph** [comment]
Thanks for your contribution.

**Pull request merged**
